# config.py
EAR_THRESHOLD = 0.25
EAR_SEMI_THRESHOLD = 0.28
MAR_THRESHOLD = 0.60
DROWSY_FRAMES = 10
ALARM_SOUND = "assets/sounds/alarm.wav"

# Advanced Features
CALIBRATION_FRAMES = 60
SMOOTHING_WINDOW = 3
EAR_DROP_PERCENTAGE = 0.75
MAR_RISE_PERCENTAGE = 1.5

# Distraction & Head Pose
GAZE_THRESH_L = 0.45 
GAZE_THRESH_R = 0.55
GAZE_FRAMES = 40 # ~1.5 Seconds for normal distraction
HEAD_DROP_THRESHOLD = 0.35 
HEAD_TURN_THRESH_L = 0.38 
HEAD_TURN_THRESH_R = 0.62
CRITICAL_DISTRACTION_FRAMES = 55 # ~2 Seconds for both head + eyes away
GAZE_HOLD_FRAMES = 20   # ~2 seconds (depends on FPS)